# Generated by Django 5.2.14 on 2026-05-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_category_tasks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
